name: Close PRs from Other Branches

on:
  pull_request:
   branches:
    - 'stage'
    - 'prod' 

jobs:
  close_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging refs 
        run: |-
          echo base ${{ github.base_ref }}
          echo head ${{ github.head_ref }}

      - name: Check PR branch
        if: ${{ github.base_ref == 'stage' }}
        run: |
          if [ ${{ github.head_ref }} != "dev" ]; then
            echo "Closing PR because it is not from DEV"
            curl -L \
              -X PATCH \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER" \
              -d '{"title":"Forbidden PR","body":"PRs from feature branches is forbidden","state":"closed","base":"${{github.base_ref}}"}'
          else
            echo "PR is from the DEV branch. No action required."
          fi
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
