name: Close PRs from Other Branches

on:
  pull_request:
   branches:
    - 'stage'
    - 'prod' 

jobs:
  close_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging refs 
        run: |-
          echo base ${{ github.base_ref }}
          echo head ${{ github.head_ref }}

      - name: Check PR branch
        if: ${{ github.base_ref == 'stage' && github.head_ref != 'dev'}}
        run: |
            echo "Closing PR because it is not from DEV"
            gh pr close $PR_NUMBER --repo $GITHUB_REPOSITORY

        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
