name: Close PRs from Other Branches

on:
  pull_request:
   branches:
    - 'stage'
    - 'prod' 

jobs:
  close_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Debugging refs 
        run: |-
          echo base ${{ github.base_ref }}
          echo head ${{ github.head_ref }}

      - name: Check PR branch
        if: ${{ github.base_ref == 'stage' }}
        run: |
          if [ ${{ github.head_ref }} != "dev" ]; then
            echo "Closing PR because it is not from DEV"
            gh pr close $PR_NUMBER --repo $GITHUB_REPOSITORY
          else
            echo "PR is from the DEV branch. No action required."
          fi
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
