name: Do something after merge

on:
  pull_request:
    branches:
      - 'dev'
      - 'stage'
      - 'prod'
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |-
          echo PR was merged successfully.
        shell: bash